version: "2"
linters:
  settings:
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        text: weak cryptographic primitive
      - linters:
          - gosec
        text: "G107:"
      - linters:
          - gosec
        text: "G404:"
      - linters:
          - gosec
        text: "G101:"
      - linters:
          - gosec
        text: "G115:"
      - linters:
          - gosec
        text: "G306:"
      - linters:
          - misspell
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
