# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download

builds:
  - id: watcher-darwin-amd64
    ldflags: -s -w -X github.com/DaRealFreak/watcher-go.Version={{.Version}} -X github.com/DaRealFreak/watcher-go.BuildDate={{.Date}} -X github.com/DaRealFreak/watcher-go.CommitHash={{ .ShortCommit }}
    binary: watcher
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    main: ./main.go
    goos:
      - darwin
    goarch:
      - amd64
  - id: watcher-linux-amd64
    ldflags: -s -w -X github.com/DaRealFreak/watcher-go.Version={{.Version}} -X github.com/DaRealFreak/watcher-go.BuildDate={{.Date}} -X github.com/DaRealFreak/watcher-go.CommitHash={{ .ShortCommit }}
    binary: watcher
    env:
      - CGO_ENABLED=1
    main: ./main.go
    goos:
      - linux
    goarch:
      - amd64
  - id: watcher-windows-amd64
    ldflags: -s -w -X github.com/DaRealFreak/watcher-go.Version={{.Version}} -X github.com/DaRealFreak/watcher-go.BuildDate={{.Date}} -X github.com/DaRealFreak/watcher-go.CommitHash={{ .ShortCommit }}
    binary: watcher
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    main: ./main.go
    goos:
      - windows
    goarch:
      - amd64

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{.ProjectName}}-v{{.Version}}-{{.Os}}-{{.Arch}}"
    replacements:
      amd64: 64bit
      386: 32bit
      arm: ARM
      arm64: ARM64
      darwin: macOS
      linux: Linux
      windows: Windows
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: DaRealFreak
    name: watcher-go
  disable: false
  draft: false
  prerelease: false
  name_template: "{{.Tag}}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^[DOC]:'
      - '^Bump'
      - Merge pull request
      - Merge branch