version: "3"

services:
  app_goreleaser:
    image: diebaumchen/watcher-go:latest
    build:
      context: ..
      dockerfile: .build/Dockerfile
      args:
        GO_VERSION: 1.17.3
    working_dir: /go/src/github.com/DaRealFreak/watcher-go
    privileged: true
    volumes:
      - ./../:/go/src/github.com/DaRealFreak/watcher-go
    env_file:
      - github.env
    command: goreleaser release --rm-dist
