name: 'goreleaser'

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

env:
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  SENTRY_ORG: ${{ secrets.SENTRY_ORG }}

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install sentry-cli
        run: curl -sL https://sentry.io/get-cli/ | bash

      - name: Set GitHub Token for GoReleaser
        run: |
          touch .build/github.env
          echo GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} >> .build/github.env

      - name: Cross compile and create GitHub release
        run: docker-compose -f .build/docker-compose.yml run app_goreleaser
        timeout-minutes: 15

      - name: Create release
        run: sentry-cli releases new -p watcher-go "$(sentry-cli releases propose-version)"

      - name: Associate commits with the release
        run: sentry-cli releases set-commits --auto "$(sentry-cli releases propose-version)" && sentry-cli releases deploys "$(sentry-cli releases propose-version)" new --env Production
