name: tests
on:
  push:
    paths:
      - '**.go'
  pull_request:
    paths:
      - '**.go'

env:
  DEVIANTART_USER: ${{ secrets.DEVIANTART_USER }}
  DEVIANTART_PASS: ${{ secrets.DEVIANTART_PASS }}
  PIXIV_SESSION_ID: ${{ secrets.PIXIV_SESSION_ID }}
  PIXIV_DEVICE_TOKEN: ${{ secrets.PIXIV_DEVICE_TOKEN }}
  PIXIV_USER: ${{ secrets.PIXIV_USER }}
  PIXIV_PASS: ${{ secrets.PIXIV_PASS }}
  TWITTER_CLIENT_ID: ${{ secrets.TWITTER_CLIENT_ID }}
  TWITTER_CLIENT_SECRET: ${{ secrets.TWITTER_CLIENT_SECRET }}

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Test
        run: go test ./...