name: Twitter
on:
  push:
    paths:
      - 'internal/modules/twitter/**'
  pull_request:
    paths:
      - 'internal/modules/twitter/**'

env:
  TWITTER_CLIENT_ID: ${{ secrets.TWITTER_CLIENT_ID }}
  TWITTER_CLIENT_SECRET: ${{ secrets.TWITTER_CLIENT_SECRET }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Test
        run: go test ./internal/modules/twitter/...