name: tests
on:
  # trigger workflow on push and pull requests on the master branch
  # disable for feature branches (since mac builds are expensive af)
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  PIXIV_SESSION_ID: ${{ secrets.PIXIV_SESSION_ID }}
  PIXIV_DEVICE_TOKEN: ${{ secrets.PIXIV_DEVICE_TOKEN }}
  PIXIV_USER: ${{ secrets.PIXIV_USER }}
  PIXIV_PASS: ${{ secrets.PIXIV_PASS }}

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Test
        run: go test ./...