name: 'Test - DeviantArt'
on:
  push:
    paths:
      - 'internal/modules/deviantart/**'
  pull_request:
    paths:
      - 'internal/modules/deviantart/**'

env:
  DEVIANTART_USER: ${{ secrets.DEVIANTART_USER }}
  DEVIANTART_PASS: ${{ secrets.DEVIANTART_PASS }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Test
        run: go test ./internal/modules/deviantart/...