name: DeviantArt
on:
  push:
    paths:
      - 'internal/modules/deviantart/**'
  pull_request:
    paths:
      - 'internal/modules/deviantart/**'

env:
  DEVIANTART_USER: ${{ secrets.DEVIANTART_USER }}
  DEVIANTART_PASS: ${{ secrets.DEVIANTART_PASS }}

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Test
        run: go test ./internal/modules/deviantart/...