name: tests
on:
  push:
    paths:
      - '**.go'
      - '!internal/modules/**'
  pull_request:
    paths:
      - '**.go'
      - '!internal/modules/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Test
        run: go test `go list ./... | grep -v internal/modules/`